#!/bin/sh
set -e

printf 'What is branch name? : '
read head
if [ -z "$head" ]; then
echo "Invalid branch name."
exit 1
fi

printf 'What is base branch name? : '
read base
if [ -z "$base" ]; then
echo 'Invalid branch name.'
exit 1
fi

printf 'What is PR title? : '
read title
if [ -z "$title" ]; then
echo 'Invalid title.'
exit 1
fi

# Commit
git checkout -b $head
git commit -m "Create PR" --allow-empty
# Push
git push -u origin $head
# PR
if [ -f .github/PULL_REQUEST_TEMPLATE.md ]; then
# TODO:template not working
hub pull-request -F .github/PULL_REQUEST_TEMPLATE.md --edit -m "$title" -b $base -h $head | xargs open -a "Google Chrome"
else
hub pull-request -m "$title" -b $base -h $head | xargs open -a "Google Chrome"
fi
